### ISSUE TITLE
Notice: Undefined index: link_button in cptbc-frontend.php on line 100

### ISSUE THREAD

**Issue by pfernandez** [ewels/cpt-bootstrap-carousel#58]
Temporarily fixed by  inserting

    if( !isset($atts['link_button']) ) {
        $atts['link_button'] = 0;
    }

at line 97.

**Comment by ewels** [comment]
Ok great, thanks! Is that the development version? If you have this on a fork do you mind submitting a pull request?

Phil

**Comment by pfernandez** [comment]
I just created the fork to submit the change-- the version I was originally using was straight out of wordpress.org.

**Comment by ewels** [comment]
Thanks for this! You can get the github version of the code now, this will then go out to WordPress in the next release (could be a while yet).
