### ISSUE TITLE
Option to add before/after caption div tags

### ISSUE THREAD

**Issue by davoaust** [ewels/cpt-bootstrap-carousel#79]
I've come across issues when implementing carousels that require a custom wrapper for the caption div. A good example would be left aligning it with page content that's in a bootstrap fixed width container - you can't do this with the basic html, you need an extra div to set the width on.

This is easily fixed by having 2 markup fields, one before the caption div and one after it.

I've forked and am about to create a pull request - let me know if you want me to change it.

**Comment by ewels** [comment]
Just merged the PR - thanks!
