### ISSUE TITLE
CPT Bootstrap Carousel

### ISSUE THREAD

**Issue by asmitarane** [ewels/CPT-Bootstrap-Carousel#89]
Is this plugin working with WordPress version 4.7.5?

**Comment by ewels** [comment]
Hi @asmitarane,

I haven't tested it myself, but I haven't heard any reports of it not working..

Phil

**Comment by asmitarane** [comment]
Actually I want to update wordpress version of my website.
Thats why I am asking about that

**Comment by ewels** [comment]
Aha, I see. Well you should be fine I think - I can't guarantee that it'll work but I'd be very surprised if it doesn't (it's quite a simple plugin and I haven't had to change anything in it for very many WordPress iterations).

Phil
