### ISSUE TITLE
Enhancement Bootstrap 4.x

### ISSUE THREAD

**Issue by danielnielsen** [ewels/CPT-Bootstrap-Carousel#91]
I have done some updating on the plugin to be compatible with bootstrap 4.x 

Who can I send the files to for revision?

**Comment by danielnielsen** [comment]
Here are my changes:

https://github.com/danielnielsen/CPT-Bootstrap-Carousel

**Comment by ewels** [comment]
Hi @danielnielsen,

This is great, thanks!

I've opened a pull request (#92) where I can review and merge the changes. Let's continue the discussion there.

Phil
