### ISSUE TITLE
Mouse over stop the slide show 

### ISSUE THREAD

**Issue by Mischu70** [ewels/CPT-Bootstrap-Carousel#99]
Hover stop the slide
When the mouse pointer is on the slide, the slide Shows stops. How can you turn that off? Many Thanks.

**Comment by ewels** [comment]
Duplicate issue, see discussion: https://github.com/ewels/CPT-Bootstrap-Carousel/issues/69#issuecomment-760372828

**Comment by Mischu70** [comment]
Hello Phil,

I think I solved the problem. I keyed in the following in my header.php
And it looks good.  
Many thanks

Michael
